AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creating serverless application model.
Globals:
  Function:
    Timeout: 3
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam_lambda
      Handler: app.handler
      Runtime: nodejs12.x
      AutoPublishAlias: production
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      DeploymentPreference:
        Type: Canary10Percent10Minutes
      CodeUri: s3://yasirassigns3bucketneww/d4b764c1092363757290f57ff1c6eb25
